version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0'  # Use the relevant Docker image for your project
    steps:
      - checkout
      - run:
          name: Build the Project
          command: |
            # Replace this with how you build your project
            ./gradlew build
            
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
