version: 2.1

jobs:
  build:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Using SonarQube Docker image
    steps:
      - checkout
      
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=my-project-key \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
